### ISSUE TITLE
Create React-APP

### ISSUE THREAD

**Issue by Tuliany** [chas-academy/u10-klippklipp-g3#3]
# Frontend

As per our stack declaration we'll be using react as our frontend. Initially we'll need a simple boilerplate to get the ball rolling. Once this is up we can start looking at our internal structure.

**Comment by axelra82** [comment]
# Frontend boilerplate

In the interest of moving things along I've pushed a boilerplate frontend for everyone to take a look at. It contains:

- a global store context
- some layout components
- basic initial custom styles
- a landing page component

I've added some commenting on the context for global state handling and the hooks used in main layout. Hopefully this will shed some light on any initial questions regarding hooks and the context hook 🤓

To anyone feeling overwhelmed, don't worry, I'm sure all of this will become much clearer once we all start working with it 😉 

**PS.** It was late and I realized just when I was wrapping up that I had been working on the main branch 😅  **Mea culpa!**

Obviously pushing to main should only be done for minor changes (e.g. typo fixes, etc), not major changes like initiating the entire frontend 😂 

Anyway, what's done is done now. Please take a look over the weekend and let me know, here or on slack, if you find any issues 👍
